render_weather_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
    display_mode:
      selector:
        select:
          options:
            - colour
            - mono
      required: false
    temperature_unit:
      selector:
        select:
          options:
            - celsius
            - fahrenheit
      required: false
    wind_speed_unit:
      selector:
        select:
          options:
            - kmh
            - mph
      required: false
send_weather_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
    display_mode:
      selector:
        select:
          options:
            - colour
            - mono
      required: false
    temperature_unit:
      selector:
        select:
          options:
            - celsius
            - fahrenheit
      required: false
    wind_speed_unit:
      selector:
        select:
          options:
            - kmh
            - mph
      required: false
    display:
      selector:
        boolean:
      required: false
render_sunrise_sunset_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
send_sunrise_sunset_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
    display:
      selector:
        boolean:
      required: false
render_moon_phase_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
send_moon_phase_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
    display:
      selector:
        boolean:
      required: false
render_xkcd_card:
  fields:
    xkcd_number:
      selector:
        number:
          min: 1
          mode: box
      required: false
    attempts:
      selector:
        number:
          min: 1
          max: 100
          mode: box
      required: false
    seed:
      selector:
        number:
          min: 1
          mode: box
      required: false
send_xkcd_card:
  fields:
    xkcd_number:
      selector:
        number:
          min: 1
          mode: box
      required: false
    attempts:
      selector:
        number:
          min: 1
          max: 100
          mode: box
      required: false
    seed:
      selector:
        number:
          min: 1
          mode: box
      required: false
    display:
      selector:
        boolean:
      required: false
render_astrology_card:
  fields:
    astrology_signs:
      selector:
        select:
          multiple: true
          options:
            - aries
            - taurus
            - gemini
            - cancer
            - leo
            - virgo
            - libra
            - scorpio
            - sagittarius
            - capricorn
            - aquarius
            - pisces
      required: false
send_astrology_card:
  fields:
    astrology_signs:
      selector:
        select:
          multiple: true
          options:
            - aries
            - taurus
            - gemini
            - cancer
            - leo
            - virgo
            - libra
            - scorpio
            - sagittarius
            - capricorn
            - aquarius
            - pisces
      required: false
    display:
      selector:
        boolean:
      required: false
