render_weather_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
    display_mode:
      selector:
        select:
          options:
            - colour
            - mono
      required: false
    temperature_unit:
      selector:
        select:
          options:
            - celsius
            - fahrenheit
      required: false
    wind_speed_unit:
      selector:
        select:
          options:
            - kmh
            - mph
      required: false
send_weather_card:
  fields:
    location_name:
      selector:
        text:
      required: false
    weather_location:
      selector:
        location:
      required: false
    latitude:
      selector:
        text:
      required: false
    longitude:
      selector:
        text:
      required: false
    display_mode:
      selector:
        select:
          options:
            - colour
            - mono
      required: false
    temperature_unit:
      selector:
        select:
          options:
            - celsius
            - fahrenheit
      required: false
    wind_speed_unit:
      selector:
        select:
          options:
            - kmh
            - mph
      required: false
    display:
      selector:
        boolean:
      required: false
